/**
 * Type declarations for the openmls-wasm package generated by wasm-pack.
 * These mirror the Rust structs exposed via wasm-bindgen.
 */

export interface WasmProvider {
  free(): void;
}

export interface WasmProviderConstructor {
  new (): WasmProvider;
}

export interface WasmIdentity {
  free(): void;
  key_package(provider: WasmProvider): WasmKeyPackage;
}

export interface WasmIdentityConstructor {
  new (provider: WasmProvider, name: string): WasmIdentity;
}

export interface WasmKeyPackage {
  free(): void;
  to_bytes(): Uint8Array;
}

export interface WasmKeyPackageStatic {
  from_bytes(bytes: Uint8Array): WasmKeyPackage;
}

export interface WasmRatchetTree {
  free(): void;
  to_bytes(): Uint8Array;
}

export interface WasmRatchetTreeStatic {
  from_bytes(bytes: Uint8Array): WasmRatchetTree;
}

export interface WasmAddMessages {
  free(): void;
  readonly commit: Uint8Array;
  readonly welcome: Uint8Array;
}

export interface WasmGroup {
  free(): void;
  export_ratchet_tree(): WasmRatchetTree;
  add_member(
    provider: WasmProvider,
    sender: WasmIdentity,
    new_member: WasmKeyPackage
  ): WasmAddMessages;
  merge_pending_commit(provider: WasmProvider): void;
  encrypt(
    provider: WasmProvider,
    sender: WasmIdentity,
    plaintext: Uint8Array
  ): Uint8Array;
  decrypt(provider: WasmProvider, ciphertext: Uint8Array): Uint8Array;
}

export interface WasmGroupStatic {
  create_new(provider: WasmProvider, founder: WasmIdentity, group_id: string): WasmGroup;
  join(provider: WasmProvider, welcome: Uint8Array, ratchet_tree: WasmRatchetTree): WasmGroup;
}

export interface OpenMlsWasmModule {
  Provider: WasmProviderConstructor;
  Identity: WasmIdentityConstructor;
  KeyPackage: WasmKeyPackageStatic & { new (...args: unknown[]): WasmKeyPackage };
  RatchetTree: WasmRatchetTreeStatic & { new (...args: unknown[]): WasmRatchetTree };
  Group: WasmGroupStatic & { new (...args: unknown[]): WasmGroup };
}
